SELECT
    task_id,
    wbs_id,
    task_code,
    task_name,
    task_type,
    is_nrc,
    parent_task_id,
    root_task_id,
    ata_chapter,
    jic_number,
    zone,
    requires_rii,
    is_ojt_eligible,
    status_code,
    target_start,
    target_end,
    actual_start,
    actual_end,
    created_at,
    updated_at,
    target_duration_hours,
    skill_code,
    is_blocked_material,
    is_blocked_tool,
    is_blocked_labor,
    is_critical_path,
    baseline_start,
    baseline_end,
    amm_reference,
    access_panel,
    estimated_hours,
    instruction_text,
    safety_warnings,
    tools_required,
    deferment_status,
    deferment_reason,
    nrc_status,
    project_id,
    origin_document,
    document_reference,
    mpd_reference,
    budgeted_labor_hours,
    p6_actual_hours,
    resource_list,
    phase_code,
    baseline_phase_code,
    frequency,
    access_panels,
    zone_area,
    is_rii,
    is_oa,
    oa_hours,
    oa_material_cost,
    oa_batch_id,
    estimated_material_cost,
    created_by,
    corrective_action,
    is_milestone,
    is_blocked_predecessor,
    is_predecessor_manual,
    pending_id,
    EXISTS (
        SELECT 1
        FROM mro_task_materials tm
        JOIN mro_materials m ON m.material_id = tm.material_id
        WHERE tm.task_id = mro_tasks.task_id
          AND (m.is_blocking_task IS TRUE OR m.is_blocking_task IS NULL)
    ) AS tem_provedoria
FROM public.mro_tasks